export const users = [
  {id:"1",name:'kenisa tetemke', image:'img3.jpg',profile:'img1.jpg' ,porfolio:'computer science | full-stack developer  ',city:'Addis Ababa Addis Ababa',about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"2",name:'abenezer tilahun', image:'img2.jpg',profile:'img3.jpg' ,porfolio:'arciologist | work at atroUniverse',city:'Addis Ababa Addis Ababa' ,about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"3",name:'besufkad bekele', image:'img3.jpg',profile:'img4.jpg' ,porfolio:'nural science | brain specialist ',city:'Addis Ababa Addis Ababa',about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"4",name:'afewerk eyob', image:'img4.jpg',profile:'img1.jpg' ,porfolio:'Docter | work at tikurAnbesa',city:'Addis Ababa Addis Ababa' ,about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"5",name:'bereket g/meskel', image:'img5.jpg',profile:'img3.jpg' ,porfolio:'mathimathisian | AI developer ',city:'Addis Ababa Addis Ababa',about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"6",name:'yonas mulat', image:'img1.jpg',profile:'img5.jpg' ,porfolio:'electrisian | contracter | student',city:'Addis Ababa Addis Ababa',about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"7",name:'gech tesfaye', image:'img3.jpg',profile:'img4.jpg' ,porfolio:'Economist | privet work ',city:'Addis Ababa Addis Ababa',about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
  {id:"8",name:'keku belay', image:'img4.jpg',profile:'img2.jpg' ,porfolio:'interprener | content creater',city:'Addis Ababa Addis Ababa',about:"I am passionate about solving problems through coding. My journey into software development began with a fascination for how technology can address real-world challenges, and over the years, I’ve built my skills in creating practical software solutions."},
]