# Generated by Django 4.2.25 on 2025-10-28 17:21

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custemuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
