# Generated by Django 4.2.25 on 2025-10-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0002_alter_custemuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custemuser',
            managers=[
            ],
        ),
    ]
