# Generated by Django 4.2.25 on 2025-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0003_alter_custemuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custemuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
